config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root "datastores#index"
  root "home#index"

  resources :datastores do
  	resources :locations
  end

  resources :datafiles do
    resources :metadata
  end

  namespace :api do
		namespace :v1 do
			resources :datastores do
  			resources :locations
  		end
		end
	end

end

app/models/datafile.rb
class Datafile < ApplicationRecord
  paginates_per 15
  validates :name, presence: true

  has_many :metadata
  has_many :locations
end

app/controllers/datafiles_controller.rb
class DatafilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_datafile, only: [:show, :edit, :update, :destroy]
  
  def index
    @datafiles = Datafile.all.order('id desc').page params[:page]
  end

  def new
    @datafile = Datafile.new
  end

  def create
    @datafile = Datafile.new(datafile_params)
    if @datafile.save
      flash[:notice] = "Datafile has been created."
      redirect_to @datafile 
    else
      flash[:alert] = "Datafile has not been created."
      render"new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @datafile.update(datafile_params)
      flash[:notice] = "Datafile has been updated."
      redirect_to @datafile
    else
      flash[:alert] = "Datafile has not been updated."
      render "edit"
    end
  end

  def destroy
    @datafile.destroy
    
    flash[:notice] = "Datafile has been destroyed."
    
    redirect_to datafiles_path
  end

  private
  def datafile_params
    params.require(:datafile).permit(:name, :size, :checksum)
  end

  def set_datafile
    @datafile = Datafile.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The datafile you were looking for could not be found."
    redirect_to datafiles_path
  end
end

app/helpers/datafiles_helper.rb
module DatafilesHelper
end

app/views/datafiles/_form.html.erb
<%= form_for(@datafile) do |f| %>
  <% if @datafile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datafile.errors.count, "error") %>
      prohibited this file from being saved:</h2>

      <ul>
      <% @datafile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </p>
    <p>
    <%= f.label :checksum %><br />
    <%= f.text_field :checksum %>
  </p>
  <%= f.submit %>
<% end %>

app/views/datafiles/edit.html.erb
<h2>Edit File</h2>

<%= render "form" %>

app/views/datafiles/index.html.erb
<% title("Datafiles") %>

<h1>Datafiles</h1>

<div class="col-md-8 text-right">
  <%= link_to "New File", new_datafile_path, class: "btn btn-success" %>
</div>

<div class="col-md-9">
<table  class="table table-striped">
  <thead>
    <tr><th>Id</th><th>Name</th><th>Size</th><th>Checksum</th><th># Locations</th></tr>
  </thead>
  <tbody>
    <% @datafiles.each do |datafile| %>
    <tr>
      <td><%= datafile.id %></td><td><%= link_to datafile.name, datafile %></td><td><%= number_to_human_size(datafile.size) %></td><td><%= datafile.checksum%></td><td><%= datafile.locations_count %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @datafiles %>
</div>

app/views/datafiles/new.html.erb
<h2>New Datafile</h2>

<%= render "form" %>

app/views/datafiles/show.html.erb
<% title(@datafile.name, "File") %>

<h2>Datafile: <%= @datafile.name %></h2>

<div class="col-md-12 text-right">
<%= link_to "Edit Datafile", edit_datafile_path(@datafile), class: "btn btn-info" %>

<%= link_to "Delete Datafile",
  datafile_path(@datafile),
  method: :delete,
  data: { confirm: "Are you sure you want to delete this file?"}, class: "btn btn-danger"
%>

<%= link_to "Add Metadata", new_datafile_metadata_path(@datafile), class: "btn btn-success" %>
</div>

<div class="row">
<div class="col-md-6">
<h2>Locations</h2>
<table  class="table table-striped">
  <thead>
    <tr><th>Datastore</th><th>Filename</th></tr>
  </thead>
  <tbody>
    <% @datafile.locations.each do |location| %>
    <tr>
      <td>#<%= location.datastore.name %></td><td><%= link_to location.path_name, [location.datastore, location] %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>


<div class="col-md-6">
<h2>Metadata</h2>
<table  class="table table-striped" id="metadata">
  <thead>
    <tr><th>Id</th><th>Value</th></tr>
  </thead>
  <tbody>
    <% @datafile.metadata.order("key asc").each do |metadata| %>
    <tr>
      <td><%= metadata.id %></td><td><%= link_to metadata, [@datafile, metadata] %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>