config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root "datastores#index"
  root "home#index"

  resources :datastores do
  	resources :locations
  end

  resources :datafiles do
    resources :metadata
  end

  namespace :api do
		namespace :v1 do
			resources :datastores do
  			resources :locations
  		end
		end
	end

end

app/models/datastore.rb
class Datastore < ApplicationRecord
  paginates_per 25

  validates :name, presence: true

  has_many :locations, dependent: :delete_all
end

app/controllers/api/v1/datastores_controller.rb
class Api::V1::DatastoresController < Api::V1::BaseController

  def index
    respond_with(Datastore.all)
  end
  
  def show
    @datastore = Datastore.includes(:locations).order("locations.path ASC, locations.name ASC").find(params[:id])

    respond_with(
      :datastore => @datastore.as_json,
      :locations => @datastore.locations.as_json,
      :files => get_referenced_files(@datastore))
  end

  def create
    #puts params
    if params[:data]
      datastore = create_datastore_from_cli(params)
    else
      datastore = Datastore.new(datastore_params)
    end
#datastore = create_datastore_from_cli(params)
    if datastore.save
      respond_with(datastore, :location => api_v1_datastore_path(datastore))
    else
      respond_with(datastore)
    end
  end

  private
  def datastore_params
    params.require(:datastore).permit(:name, :mediatype)
  end

  def create_datastore_from_cli(params)
    json = JSON.parse(params[:data])

    datastore = Datastore.new
    set_datastore_variables(datastore, json)
    add_locations(datastore, json)

    Datastore.where(id: datastore.id).first
  end

  def set_datastore_variables(datastore, json)
    datastore.name = json["name"]
    datastore.mediatype = json["mediatype"]
    datastore.save
  end

  def add_locations(datastore, json)
    json["files"][0].each do |f| 
      loc = datastore.locations.build
      loc.name = f["name"]
      loc.path = f["path"]
      loc.last_modified = f["last_modified"]
      find_or_create_datafile(loc, f)
      loc.save
    end
  end

  def find_or_create_datafile(loc, file)
    df = Datafile.find_or_create_by(checksum: file["checksum"])

    if not df.persisted?
      df.size = file["size"]
      df.name = file["name"]
      df.save!
    end

    add_or_update_metadata(df, file["metadata"])
    
    loc.datafile = df
  end

  def add_or_update_metadata(file, metadata)
    if not metadata.nil?
      metadata.each do |key, value| 
        meta = file.metadata.find_or_create_by(key: key)
        meta.value = value
        meta.save!
      end
    end
  end
  
  def get_referenced_files(datastore)
    result = Array.new
    datastore.locations.each do |loc|
      file = Array.new
      file << loc.datafile
      loc.datafile.metadata.order("key").each {|m| file << m}


      result << file
    end
    result.to_json
  end
end

app/controllers/datastores_controller.rb
class DatastoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_datastore, only: [:show, :edit, :update, :destroy]


  def index
    @datastores = Datastore.all.order('id desc').page params[:page]
  end

  def new
    @datastore = Datastore.new
  end

  def create
    @datastore = Datastore.new(datastore_params)
    if @datastore.save
      flash[:notice] = "Datastore has been created."
      redirect_to @datastore 
    else
      flash[:alert] = "Datastore has not been created."
      render "new"
    end
  end

  def show
    @ordered_locations = @datastore.locations.order('path', 'name').page params[:page]
  end

  def edit
  end

  def update
    if @datastore.update(datastore_params)
      flash[:notice] = "Datastore has been updated."
      redirect_to @datastore
    else
      flash[:alert] = "Datastore has not been updated."
      render "edit"
    end
  end

  def destroy
    @datastore.destroy
    
    flash[:notice] = "Datastore has been destroyed."
    
    redirect_to datastores_path
  end


  private
  def datastore_params
    params.require(:datastore).permit(:name, :mediatype)
  end

  def set_datastore
    @datastore = Datastore.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The datastore you were looking for could not be found."
    redirect_to datastores_path
  end

end

app/helpers/datastores_helper.rb
module DatastoresHelper
end

app/views/datastores/_form.html.erb
<%= form_for(@datastore) do |f| %>
  <% if @datastore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datastore.errors.count, "error") %>
      prohibited this datastore from being saved:</h2>

      <ul>
      <% @datastore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :mediatype %><br />
    <%= f.text_field :mediatype %>
  </p>
  <%= f.submit %>
<% end %>

app/views/datastores/edit.html.erb
<h2>Edit Datastore</h2>

<%= render "form" %>

app/views/datastores/index.html.erb
<% title("Datastores") %>

<h1>Datastores</h1>

<div class="col-md-8 text-right">
  <%= link_to "New Datastore", new_datastore_path, class: "btn btn-success" %>
  <%= link_to "New File", new_datafile_path, class: "btn btn-success" %>
</div>

<div class="col-md-8">
<table  class="table table-striped">
  <thead>
    <tr><th>Id</th><th>Name</th><th>Type</th><th>Size</th><th># Files</th></tr>
  </thead>
  <tbody>
    <% @datastores.each do |ds| %>
    <tr>
      <td><%= ds.id %></td><td><%= link_to ds.name, ds %></td><td><%= ds.mediatype %></td><td></td><td><%= ds.locations_count %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @datastores %>
</div>

app/views/datastores/show.html.erb
<% title(@datastore.name, "Datastores") %>

<h1>Datastore: <%= @datastore.name %></h1>

<div class="col-md-8 text-right">
<%= link_to "Edit Datastore", edit_datastore_path(@datastore), class: "btn btn-info" %>

<%= link_to "Delete Datastore",
  datastore_path(@datastore),
  method: :delete,
  data: { confirm: "Are you sure you want to delete this datastore?" }, class: "btn btn-danger"
%>

<%= link_to "New Location", new_datastore_location_path(@datastore), class: "btn btn-success" %>
</div>


<div class="col-md-8">
<table  class="table table-striped">
  <thead>
    <tr><th>Path</th><th>Name</th><th>Last Modified</th><th>Datafile Id</th></tr>
  </thead>
  <tbody>
    <% @ordered_locations.each do |location| %>
    <tr>
      <td><%= link_to location.path, [@datastore, location] %></td><td><%= link_to location.name, [@datastore, location] %></td><td><%= location.last_modified %></td><td>
     <%= 
        if(!location.datafile.nil?)
          link_to location.datafile_id, location.datafile
        end
        %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @ordered_locations %>
</div>